# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Auto Revert Last Merge on build/test failure
      if: failure()
      uses: RahulParmarRP/auto-revert-merge@master
      with: 
        BRANCH_NAME: master
      env: 
        GITHUB_TOKEN: ${{ secrets.AUTO_REVERT_MERGE_ACCESS_TOKEN }}
    - name: Deploy on Dev or Stage Server for CI
      run: echo "Here Step to Deploy on Development or Stage Server for CI"
